In [1]:
import numpy as np


In [3]:
##Data types and Attributes

In [4]:
a1 =np.array([1,2,4])
a1

array([1, 2, 4])

In [5]:
type(a1)

numpy.ndarray

In [6]:
a2 =np.array([[1,2.8,3.7],[3,6.7,8.9]])
a3=np.array([[[1,2,3],
              [4,5,6],
              [4,7,8]],
           [ [10,11,12],
            [45,6,7],
            [3,8,5]]])

In [11]:
a2

array([[1. , 2.8, 3.7],
       [3. , 6.7, 8.9]])

In [10]:
a3

array([[list([1, 2, 3]), list([4, 5, 6]), list([4, 7, 8])],
       [10, 11, 12],
       [45, 6, 7],
       [3, 8, 5]], dtype=object)

In [12]:
a1.shape

(3,)

In [13]:
a2.shape

(2, 3)

In [14]:
a3.shape

(4, 3)

In [15]:
a1.ndim,a2.ndim,a3.ndim

(1, 2, 2)

In [17]:
a1.dtype

dtype('int32')

In [18]:
a2.dtype

dtype('float64')

In [19]:
a3.size

12

In [20]:
a1.size,a2.size,a3.size

(3, 6, 12)

In [21]:
type(a1)

numpy.ndarray

In [22]:
#create a dataframe from numpy array

In [23]:
import pandas as pd

In [24]:
df =pd.DataFrame(a2)
df

0    1    2
0  1.0  2.8  3.7
1  3.0  6.7  8.9

In [25]:
df2=pd.DataFrame(a3)

df2

0          1          2
0  [1, 2, 3]  [4, 5, 6]  [4, 7, 8]
1         10         11         12
2         45          6          7
3          3          8          5

In [26]:
# creating numpy arrays

In [27]:
sample_array= np.array([1,2,3])
sample_array

array([1, 2, 3])

In [29]:
ones =np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [30]:
ones.dtype

dtype('float64')

In [31]:
type(ones)

numpy.ndarray

In [32]:
zeros =np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [33]:
range_array =np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [35]:
random_array =np.random.randint(0,10,size=(3,5))

In [36]:
random_array

array([[7, 3, 2, 6, 2],
       [4, 8, 2, 0, 4],
       [5, 6, 6, 2, 6]])

In [37]:
random_array.shape

(3, 5)

In [38]:
random_array2=np.random.random((5,3))
random_array2

array([[0.3376403 , 0.34696161, 0.86542657],
       [0.81397182, 0.09119976, 0.50266861],
       [0.2899099 , 0.71143249, 0.65527062],
       [0.35427513, 0.94762109, 0.64909153],
       [0.94834995, 0.89766603, 0.16007576]])

In [39]:
random_array2.shape

(5, 3)

In [49]:
random_array3=np.random.rand(5,3)
random_array3

array([[0.55131463, 0.79716136, 0.52578757],
       [0.10177014, 0.11006089, 0.46990976],
       [0.25007252, 0.02553077, 0.13305673],
       [0.35339944, 0.97632629, 0.84376774],
       [0.07947236, 0.32511916, 0.01411056]])

In [50]:
np.random.seed()

In [64]:
np.random.seed(seed=0)
random_array4 =np.random.randint(10,size=(5,3))
random_array4


array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [69]:
np.random.seed(seed=7)
random_array5=np.random.random((5,3))
random_array5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])