In [1]:
import numpy as np

##DataTypes and Attribbutes

In [2]:
a1 =np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1
    )

numpy.ndarray

In [4]:
a2=np.array([[1,2.0,3.3],
           [4,5,6.5]])

a3=([[[1,2,3,],
     [4,5,6],
     [7,8,9]],
    [[10,11,12],
    [13,14,15],
    [16,17,18]]])

In [5]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [6]:
a3

[[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]]

In [7]:
a1.shape

(3,)

In [8]:
a2.shape

(2, 3)

In [9]:
a3.shape


AttributeError: 'list' object has no attribute 'shape'

In [ ]:
a1.ndim

In [ ]:
a1.ndim, a2.ndim ,a3.ndim

In [10]:
a2.ndim

2

In [11]:
a1.dtype

dtype('int32')

In [12]:
a2.dtype

dtype('float64')

In [13]:
a1.size

3

In [14]:
type(a1)

numpy.ndarray

In [15]:
type(a2 )

numpy.ndarray

#create a datafarame from numpy arrat

In [16]:
import pandas as pd

df =pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

#creating numpy arrays

In [17]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [18]:
sample_array.dtype

dtype('int32')

In [19]:
ones=np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
ones.dtype

dtype('float64')

In [21]:
type(ones)

numpy.ndarray

In [22]:
zeros =np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
range_array=np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [24]:
random_array=np.random.randint(0,10,size=(3,5))
random_array

array([[0, 5, 0, 3, 1],
       [1, 9, 5, 1, 7],
       [7, 1, 4, 2, 0]])

In [25]:
random_array.size

15

In [26]:
random_array.shape

(3, 5)

In [27]:
random_array2=np.random.random((5,3))
random_array2

array([[0.29177695, 0.3751891 , 0.66716027],
       [0.13788917, 0.56075351, 0.75289473],
       [0.47162486, 0.06987595, 0.84968696],
       [0.19604845, 0.04026291, 0.16741268],
       [0.32402196, 0.34210605, 0.44364841]])

In [28]:
random_array2.shape

(5, 3)

In [29]:
random_array3=np.random.rand(5,3)
random_array3

array([[0.79392539, 0.72893508, 0.34323162],
       [0.28500567, 0.1623589 , 0.67997038],
       [0.7881953 , 0.95594576, 0.12844194],
       [0.53492962, 0.39033288, 0.58166383],
       [0.14453019, 0.88977316, 0.08700984]])

In [30]:
np.random.seed()

In [31]:
print("hello world")

hello world


In [36]:

np.random.seed(seed=0)
random_array4=np.random.randint(10,size=(5,3))
random_array4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [33]:
np.random.seed(seed=7)
random_array5=np.random.random((5,3))
random_array5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

#viewing arrys 

In [35]:
np.unique(random_array_4)

NameError: name 'random_array_4' is not defined

In [37]:
random_array4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [38]:
np.unique(random_array_4)

NameError: name 'random_array_4' is not defined

In [39]:
a=np.unique(random_array4)
a


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
a1


array([1, 2, 3])

In [41]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [42]:
a3

[[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]]

In [43]:
a1[0]

1

In [44]:
a2[0]

array([1. , 2. , 3.3])

In [45]:
a2.shape



(2, 3)

In [46]:
a3.shape

AttributeError: 'list' object has no attribute 'shape'

In [47]:
a3


[[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]]

In [48]:
a3.shape

AttributeError: 'list' object has no attribute 'shape'

In [49]:
a2[1][2]

6.5

In [50]:
a3[:2,:2,:2]

TypeError: list indices must be integers or slices, not tuple

In [52]:
a4=np.random.randint(10,size=(2,3,4,5))
a4

array([[[[6, 7, 7, 8, 1],
         [5, 9, 8, 9, 4],
         [3, 0, 3, 5, 0],
         [2, 3, 8, 1, 3]],

        [[3, 3, 7, 0, 1],
         [9, 9, 0, 4, 7],
         [3, 2, 7, 2, 0],
         [0, 4, 5, 5, 6]],

        [[8, 4, 1, 4, 9],
         [8, 1, 1, 7, 9],
         [9, 3, 6, 7, 2],
         [0, 3, 5, 9, 4]]],


       [[[4, 6, 4, 4, 3],
         [4, 4, 8, 4, 3],
         [7, 5, 5, 0, 1],
         [5, 9, 3, 0, 5]],

        [[0, 1, 2, 4, 2],
         [0, 3, 2, 0, 7],
         [5, 9, 0, 2, 7],
         [2, 9, 2, 3, 3]],

        [[2, 3, 4, 1, 2],
         [9, 1, 4, 6, 8],
         [2, 3, 0, 0, 6],
         [0, 6, 3, 3, 8]]]])

a4.shape

In [53]:
a4.shape

(2, 3, 4, 5)

In [54]:
a4.shape ,a4.ndim

((2, 3, 4, 5), 4)

In [55]:
a5 =np.random.randint(10,size=(3,2,5,4))
a5

array([[[[8, 8, 2, 3],
         [2, 0, 8, 8],
         [3, 8, 2, 8],
         [4, 3, 0, 4],
         [3, 6, 9, 8]],

        [[0, 8, 5, 9],
         [0, 9, 6, 5],
         [3, 1, 8, 0],
         [4, 9, 6, 5],
         [7, 8, 8, 9]]],


       [[[2, 8, 6, 6],
         [9, 1, 6, 8],
         [8, 3, 2, 3],
         [6, 3, 6, 5],
         [7, 0, 8, 4]],

        [[6, 5, 8, 2],
         [3, 9, 7, 5],
         [3, 4, 5, 3],
         [3, 7, 9, 9],
         [9, 7, 3, 2]]],


       [[[3, 9, 7, 7],
         [5, 1, 2, 2],
         [8, 1, 5, 8],
         [4, 0, 2, 5],
         [5, 0, 8, 1]],

        [[1, 0, 3, 8],
         [8, 4, 4, 0],
         [9, 3, 7, 3],
         [2, 1, 1, 2],
         [1, 4, 2, 5]]]])

#get the first 4 num in array

#### 

In [57]:
a4[:,:,:,4]

array([[[1, 4, 0, 3],
        [1, 7, 0, 6],
        [9, 9, 2, 4]],

       [[3, 3, 1, 5],
        [2, 7, 7, 3],
        [2, 8, 6, 8]]])

##### a6 = np.random.randint




In [58]:
a6=np.random.randint(6,size=(2,5,4,3))
a6

array([[[[5, 4, 4],
         [5, 5, 2],
         [3, 5, 3],
         [1, 2, 4]],

        [[3, 3, 1],
         [1, 5, 5],
         [1, 1, 2],
         [0, 3, 1]],

        [[4, 3, 1],
         [1, 2, 0],
         [0, 2, 4],
         [0, 4, 3]],

        [[3, 0, 0],
         [3, 5, 3],
         [0, 3, 0],
         [5, 2, 1]],

        [[0, 4, 0],
         [3, 4, 4],
         [1, 0, 2],
         [4, 4, 2]]],


       [[[4, 3, 2],
         [3, 0, 5],
         [5, 5, 0],
         [0, 5, 3]],

        [[4, 4, 5],
         [2, 2, 4],
         [1, 3, 3],
         [3, 1, 2]],

        [[5, 2, 3],
         [5, 2, 3],
         [4, 4, 2],
         [5, 1, 2]],

        [[5, 0, 3],
         [0, 2, 4],
         [3, 2, 1],
         [2, 1, 4]],

        [[5, 1, 0],
         [5, 0, 0],
         [0, 0, 1],
         [0, 3, 1]]]])

In [59]:
a6[:,:,:,:2]

array([[[[5, 4],
         [5, 5],
         [3, 5],
         [1, 2]],

        [[3, 3],
         [1, 5],
         [1, 1],
         [0, 3]],

        [[4, 3],
         [1, 2],
         [0, 2],
         [0, 4]],

        [[3, 0],
         [3, 5],
         [0, 3],
         [5, 2]],

        [[0, 4],
         [3, 4],
         [1, 0],
         [4, 4]]],


       [[[4, 3],
         [3, 0],
         [5, 5],
         [0, 5]],

        [[4, 4],
         [2, 2],
         [1, 3],
         [3, 1]],

        [[5, 2],
         [5, 2],
         [4, 4],
         [5, 1]],

        [[5, 0],
         [0, 2],
         [3, 2],
         [2, 1]],

        [[5, 1],
         [5, 0],
         [0, 0],
         [0, 3]]]])

In [60]:
a6[:,:,:,:1]

array([[[[5],
         [5],
         [3],
         [1]],

        [[3],
         [1],
         [1],
         [0]],

        [[4],
         [1],
         [0],
         [0]],

        [[3],
         [3],
         [0],
         [5]],

        [[0],
         [3],
         [1],
         [4]]],


       [[[4],
         [3],
         [5],
         [0]],

        [[4],
         [2],
         [1],
         [3]],

        [[5],
         [5],
         [4],
         [5]],

        [[5],
         [0],
         [3],
         [2]],

        [[5],
         [5],
         [0],
         [0]]]])

#maipulating and comparing arrys

In [61]:
a1

array([1, 2, 3])

In [62]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [63]:
ones=np.ones(3)

In [64]:
ones

array([1., 1., 1.])

In [65]:
a1+ones

array([2., 3., 4.])

In [66]:
a1-ones

array([0., 1., 2.])

In [67]:
a1*ones

array([1., 2., 3.])

In [68]:
a1/ones

array([1., 2., 3.])

In [69]:
a1%ones


array([0., 0., 0.])

In [70]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [71]:
a2+ones


array([[2. , 3. , 4.3],
       [5. , 6. , 7.5]])

In [72]:
a1

array([1, 2, 3])

In [73]:
a3

[[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]]

In [74]:
a2*a3

ValueError: operands could not be broadcast together with shapes (2,3) (2,3,3) 

In [75]:
a2.shape

(2, 3)

In [76]:
a3.shape

AttributeError: 'list' object has no attribute 'shape'

In [77]:
a3.shape


AttributeError: 'list' object has no attribute 'shape'

In [78]:
a1/ones

array([1., 2., 3.])

In [79]:
a2//a1

array([[1., 1., 1.],
       [4., 2., 2.]])

//remover the decimals

In [80]:
a2**2

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [81]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [82]:
a1%2

array([1, 0, 1], dtype=int32)

In [83]:
a2%2

array([[1. , 0. , 1.3],
       [0. , 1. , 0.5]])

In [84]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [85]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])