In [1]:
import numpy as np

##DataTypes and Attribbutes

In [3]:
a1 =np.array([1,2,3])
a1

array([1, 2, 3])

In [4]:
type(a1
    )

numpy.ndarray

In [11]:
a2=np.array([[1,2.0,3.3],
           [4,5,6.5]])

a3=([[[1,2,3,],
     [4,5,6],
     [7,8,9]],
    [[10,11,12],
    [13,14,15],
    [16,17,18]]])

In [12]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [13]:
a3

[[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[10, 11, 12], [13, 14, 15], [16, 17, 18]]]

In [15]:
a1.shape

(3,)

In [16]:
a2.shape

(2, 3)

In [17]:
a3.shape


AttributeError: 'list' object has no attribute 'shape'

In [20]:
a1.ndim

1

In [21]:
a1.ndim, a2.ndim ,a3.ndim

AttributeError: 'list' object has no attribute 'ndim'

In [22]:
a2.ndim

2

In [23]:
a1.dtype

dtype('int32')

In [24]:
a2.dtype

dtype('float64')

In [47]:
a1.size

3

In [28]:
type(a1)

numpy.ndarray

In [29]:
type(a2 )

numpy.ndarray

#create a datafarame from numpy arrat

In [31]:
import pandas as pd

df =pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

#creating numpy arrays

In [33]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [34]:
sample_array.dtype

dtype('int32')

In [35]:
ones=np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [36]:
ones.dtype

dtype('float64')

In [37]:
type(ones)

numpy.ndarray

In [38]:
zeros =np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [39]:
range_array=np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [40]:
random_array=np.random.randint(0,10,size=(3,5))
random_array

array([[6, 5, 1, 3, 9],
       [6, 9, 1, 6, 8],
       [1, 9, 7, 2, 5]])

In [41]:
random_array.size

15

In [42]:
random_array.shape

(3, 5)

In [43]:
random_array2=np.random.random((5,3))
random_array2

array([[0.87788629, 0.45293127, 0.85866033],
       [0.74560524, 0.56652499, 0.88507268],
       [0.8105727 , 0.41120097, 0.28092898],
       [0.50814945, 0.65788942, 0.07591599],
       [0.35639334, 0.6339783 , 0.31063206]])

In [44]:
random_array2.shape

(5, 3)

In [45]:
random_array3=np.random.rand(5,3)
random_array3

array([[0.93134693, 0.68913048, 0.95171374],
       [0.64997575, 0.69129297, 0.0076115 ],
       [0.54868318, 0.00236377, 0.11670768],
       [0.35353396, 0.54591346, 0.04960133],
       [0.74280932, 0.14239181, 0.22949773]])

In [46]:
np.random.seed()

In [48]:
print("hello world")

hello world


In [60]:

np.random.seed(seed=0)
random_array4=np.random.randint(10,size=(5,3))
random_array4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [61]:
np.random.seed(seed=7)
random_array5=np.random.random((5,3))
random_array5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])